// Main Plugin
Zombie_TheHero3.amxx debug
zb3ex_core_attachment.amxx debug

// Addon Plugins
zb3ex_addon_weapon.amxx debug
zb3ex_addon_unprecache.amxx debug
zb3ex_addon_supplybox_items.amxx debug
zb3ex_addon_supplybox.amxx debug
zb3ex_addon_effect_killer.amxx debug
zb3ex_addon_information.amxx debug

// Hero Weapons
zb3ex_sub_hero_wpn2.amxx

// Extra Plugins
zb3ex_extra_item.amxx debug
zb3ex_item_zombie_a.amxx debug
zb3ex_item_human_a.amxx debug

// Zombie Classes
zb3ex_zclass_banshee2.amxx debug
zb3ex_zclass_deimos2.amxx debug
zb3ex_zclass_light2.amxx debug
zb3ex_zclass_regular2.amxx debug
;zb3ex_zclass_stamper2.amxx debug
zb3ex_zclass_stingfinger2.amxx debug
zb3ex_zclass_voodoo2.amxx debug

// Secondary Weapons
zb3ex_sec_usp.amxx debug
zb3ex_sec_elite.amxx debug
zb3ex_sec_deagle.amxx debug

// Primary Weapons
zb3ex_pri_m4a1.amxx debug
zb3ex_pri_ak47.amxx debug
zb3ex_pri_xm1014.amxx debug

// Melee Weapons
zb3ex_melee_seal-knife.amxx debug

